(dp1
S'output'
p2
S"<type 'exceptions.AttributeError'> 'dict' object has no attribute 'password'"
p3
sS'layer'
p4
S'/home/bemobi/Downloads/web2py/applications/touch_pay_client/controllers/default.py'
p5
sS'code'
p6
S'<code object <module> at 0x7f44f8da3830, file "/home/bemobi/Downloads/web2py/applications/touch_pay_client/controllers/default.py", line 10>'
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "/home/bemobi/Downloads/web2py/gluon/restricted.py", line 219, in restricted\n    exec(ccode, environment)\n  File "/home/bemobi/Downloads/web2py/applications/touch_pay_client/controllers/default.py", line 91, in <module>\n  File "/home/bemobi/Downloads/web2py/gluon/globals.py", line 409, in <lambda>\n    self._caller = lambda f: f()\n  File "/home/bemobi/Downloads/web2py/applications/touch_pay_client/controllers/default.py", line 33, in find_finger\n    print obj.password\nAttributeError: \'dict\' object has no attribute \'password\'\n'
p11
s.